# Generated by Django 5.0.6 on 2024-07-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitationkey",
            name="is_forever",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("family", "Family"),
                    ("friends", "Friends"),
                    ("acquaintance", "Acquaintance"),
                    ("student", "Student"),
                ],
                default="family",
                max_length=20,
            ),
        ),
    ]
