# Generated by Django 5.0.6 on 2024-07-06 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress_portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="todo_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todo_items",
                to="progress_portal.project",
            ),
        ),
        migrations.DeleteModel(
            name="ToDoList",
        ),
    ]
