# Generated by Django 5.0.6 on 2024-07-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress_portal", "0003_lifegoal_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lifegoal",
            name="icon",
            field=models.FileField(
                blank=True, default="icons/default_icon.png", upload_to="icons/"
            ),
        ),
    ]
