# Generated by Django 5.0.6 on 2024-07-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_quest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="hint",
            field=models.TextField(blank=True, help_text="Hint for the question"),
        ),
    ]
