# Generated by Django 5.0.6 on 2024-07-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_quest", "0002_question_hint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useranswer",
            name="selected_answer",
        ),
        migrations.AddField(
            model_name="question",
            name="blanks_answer",
            field=models.TextField(
                blank=True,
                help_text="Correct answer for Fill in the Blanks questions. Use underscores to represent blanks, e.g., 'The capital of France is _Paris_.'",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="choice_a",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="question",
            name="choice_b",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="question",
            name="choice_c",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="question",
            name="choice_d",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="question",
            name="correct_choice",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="is_true",
            field=models.BooleanField(
                blank=True, help_text="For True/False questions", null=True
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="fill_blanks_answer",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="selected_choice",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="true_false_answer",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
