# Generated by Django 5.0.6 on 2024-07-15 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exam_quest", "0003_remove_useranswer_selected_answer_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Answer",
        ),
    ]
